apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend
  - frontend

namespace: study-app
namePrefix: dev-

images:
  - name: backend
    newTag: dev
  - name: frontend
    newTag: dev
