apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend
  - frontend

namespace: study-app
namePrefix: dev-

images:
  - name: ghcr.io/santiagobermudezparra/study-app-api:latest
    newTag: backend-v0.5.0
  - name: ghcr.io/santiagobermudezparra/study-app-web:latest
    newTag: frontend-web-v0.3.0
